CREATE TABLE "payment_account" (
    "unid" VARCHAR(36) NOT NULL,
    "service_id" VARCHAR(128),
    "service_name" VARCHAR(1024),
    "dept_id" VARCHAR(128),
    "dept_name" VARCHAR(1024),
    "channel" VARCHAR(2),
    "tpv" VARCHAR(128),
    "bind" VARCHAR(2),
    "create_time" VARCHAR(32) NOT NULL,
    "modify_time" VARCHAR(32) NOT NULL,
    PRIMARY KEY ("unid")
);
CREATE INDEX "service_id" ON "payment_account" ("service_id");
CREATE INDEX "dept_id" ON "payment_account" ("dept_id");
CREATE INDEX "bind" ON "payment_account" ("bind");

CREATE TABLE "payment_account_ardz" (
    "unid" VARCHAR(36) NOT NULL,
    "service_id" VARCHAR(128),
    "service_name" VARCHAR(1024),
    "dept_id" VARCHAR(128),
    "dept_name" VARCHAR(1024),
    "channel" VARCHAR(2),
    "tpv" VARCHAR(128),
    "bind" VARCHAR(2),
    "create_time" VARCHAR(32) NOT NULL,
    "modify_time" VARCHAR(32) NOT NULL,
    PRIMARY KEY ("unid")
);
CREATE INDEX "service_id" ON "payment_account_ardz" ("service_id");
CREATE INDEX "dept_id" ON "payment_account_ardz" ("dept_id");
CREATE INDEX "bind" ON "payment_account_ardz" ("bind");

CREATE TABLE "payment_account_enus" (
    "unid" VARCHAR(36) NOT NULL,
    "service_id" VARCHAR(128),
    "service_name" VARCHAR(1024),
    "dept_id" VARCHAR(128),
    "dept_name" VARCHAR(1024),
    PRIMARY KEY ("unid")
);
CREATE INDEX "service_id" ON "payment_account_enus" ("service_id");
CREATE INDEX "dept_id" ON "payment_account_enus" ("dept_id");

CREATE TABLE "payment_account_frfr" (
    "unid" VARCHAR(36) NOT NULL,
    "service_id" VARCHAR(128),
    "service_name" VARCHAR(1024),
    "dept_id" VARCHAR(128),
    "dept_name" VARCHAR(1024),
    "channel" VARCHAR(2),
    "tpv" VARCHAR(128),
    "bind" VARCHAR(2),
    "create_time" VARCHAR(32) NOT NULL,
    "modify_time" VARCHAR(32) NOT NULL,
    PRIMARY KEY ("unid")
);
CREATE INDEX "service_id" ON "payment_account_frfr" ("service_id");
CREATE INDEX "dept_id" ON "payment_account_frfr" ("dept_id");
CREATE INDEX "bind" ON "payment_account_frfr" ("bind");

CREATE TABLE "payment_channel" (
    "unid" VARCHAR(32) NOT NULL,
    "channel" VARCHAR(2) NOT NULL,
    "account" VARCHAR(255),
    "payment_password" VARCHAR(512),
    "create_time" VARCHAR(32) NOT NULL,
    "modify_time" VARCHAR(32) NOT NULL,
    PRIMARY KEY ("unid")
);

CREATE TABLE "payment_order_number" (
    "id" BIGINT(20) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "biz_type" VARCHAR(63) NOT NULL,
    "begin_init_id" BIGINT(20),
    "begin_id" BIGINT(20) NOT NULL,
    "end_init_id" BIGINT(20),
    "end_id" BIGINT(20),
    "max_id" BIGINT(20) NOT NULL,
    "step" INT(11),
    "delta" INT(11) NOT NULL,
    "remainder" INT(11) NOT NULL,
    "begin_string_array" VARCHAR(1000),
    "this_use_begin_index" INT(11),
    "create_time" TIMESTAMP NOT NULL,
    "update_time" TIMESTAMP NOT NULL,
    "version" BIGINT(20) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "payment_refund_order" (
    "unid" VARCHAR(32) NOT NULL,
    "payment_app_id" VARCHAR(64) NOT NULL,
    "order_id" VARCHAR(32) NOT NULL,
    "order_number" VARCHAR(32) NOT NULL,
    "refund_origin" VARCHAR(4) NOT NULL,
    "refund_ip" VARCHAR(64) NOT NULL,
    "refund_channel" VARCHAR(4) NOT NULL,
    "refund_id" VARCHAR(255),
    "refund_amount" BIGINT(20) NOT NULL,
    "currency" VARCHAR(4) NOT NULL,
    "goods_order_id" VARCHAR(255) NOT NULL,
    "goods_order_number" VARCHAR(255),
    "goods_order_name" VARCHAR(512),
    "goods_service_id" VARCHAR(255),
    "goods_service_name" VARCHAR(512),
    "goods_dept_id" VARCHAR(255),
    "goods_dept_name" VARCHAR(255),
    "goods_area_code" VARCHAR(255),
    "goods_area_name" VARCHAR(255),
    "description" VARCHAR(512),
    "bank_order_id" VARCHAR(255),
    "success_callback_url" VARCHAR(512),
    "fail_callback_url" VARCHAR(512),
    "fail_code" VARCHAR(64),
    "fail_message" TEXT,
    "language_code" VARCHAR(8) NOT NULL,
    "refund_status" VARCHAR(4) NOT NULL,
    "refund_request" TEXT,
    "refund_response" LONGTEXT,
    "create_time" VARCHAR(32) NOT NULL,
    "modify_time" VARCHAR(32) NOT NULL,
    "refund_time" VARCHAR(32),
    "merchant_account" VARCHAR(255),
    "operator_id" VARCHAR(64),
    "operator_name" VARCHAR(255),
    "user_id" VARCHAR(64),
    "user_name" VARCHAR(255),
    "task_id" VARCHAR(255),
    "payee_id" VARCHAR(64),
    "payee_name" VARCHAR(255),
    "merchant_id" VARCHAR(255),
    "merchant_password" VARCHAR(512),
    PRIMARY KEY ("unid")
);
CREATE INDEX "bank_order_id" ON "payment_refund_order" ("bank_order_id");
CREATE INDEX "goods_order_id" ON "payment_refund_order" ("goods_order_id");
CREATE INDEX "refund_status" ON "payment_refund_order" ("refund_status");
CREATE INDEX "order_id" ON "payment_refund_order" ("order_id");
CREATE INDEX "order_number" ON "payment_refund_order" ("order_number");

CREATE TABLE "payment_register_item" (
    "unid" VARCHAR(32) NOT NULL,
    "order_id" VARCHAR(32) NOT NULL,
    "item_id" VARCHAR(512),
    "item_name" VARCHAR(1024) NOT NULL,
    "amount" BIGINT(20) NOT NULL,
    "create_time" VARCHAR(32) NOT NULL,
    "modify_time" VARCHAR(32) NOT NULL,
    PRIMARY KEY ("unid")
);

CREATE TABLE "payment_register_order" (
    "unid" VARCHAR(32) NOT NULL,
    "payment_app_id" VARCHAR(64) NOT NULL,
    "order_number" VARCHAR(32) NOT NULL,
    "payer_origin" VARCHAR(4) NOT NULL,
    "payer_ip" VARCHAR(64) NOT NULL,
    "payer_channel" VARCHAR(4) NOT NULL,
    "payer_id" VARCHAR(255),
    "merchant_id" VARCHAR(255),
    "merchant_account" VARCHAR(255),
    "merchant_password" VARCHAR(512),
    "goods_order_id" VARCHAR(255) NOT NULL,
    "goods_order_name" VARCHAR(512),
    "goods_order_number" VARCHAR(255),
    "goods_service_id" VARCHAR(128),
    "goods_service_name" VARCHAR(512),
    "goods_dept_id" VARCHAR(128),
    "goods_dept_name" VARCHAR(255),
    "goods_area_code" VARCHAR(128),
    "goods_area_name" VARCHAR(255),
    "payment_amount" BIGINT(20) NOT NULL,
    "refund_amount" BIGINT(20) NOT NULL,
    "total_amount" BIGINT(20) NOT NULL,
    "currency" VARCHAR(4) NOT NULL,
    "description" VARCHAR(512),
    "bank_order_id" VARCHAR(255),
    "success_callback_url" VARCHAR(512),
    "fail_callback_url" VARCHAR(512),
    "language_code" VARCHAR(8) NOT NULL,
    "order_status" VARCHAR(4) NOT NULL,
    "register_request" TEXT,
    "register_response" LONGTEXT,
    "confirm_request" TEXT,
    "confirm_response" LONGTEXT,
    "udf1" VARCHAR(255),
    "udf2" VARCHAR(255),
    "udf3" VARCHAR(255),
    "udf4" VARCHAR(255),
    "udf5" VARCHAR(255),
    "create_time" VARCHAR(32) NOT NULL,
    "modify_time" VARCHAR(32) NOT NULL,
    "register_time" VARCHAR(32),
    "confirm_time" VARCHAR(32),
    "data_status" CHAR(2) NOT NULL,
    "form_url" VARCHAR(512),
    "fail_code" VARCHAR(64),
    "fail_message" TEXT,
    "user_id" VARCHAR(64),
    "user_name" VARCHAR(255),
    "task_id" VARCHAR(64),
    "payee_id" VARCHAR(64),
    "payee_name" VARCHAR(255),
    PRIMARY KEY ("unid")
);
CREATE INDEX "bank_order_id" ON "payment_register_order" ("bank_order_id");
CREATE INDEX "goods_order_id" ON "payment_register_order" ("goods_order_id");
CREATE INDEX "order_status" ON "payment_register_order" ("order_status");

CREATE TABLE "payment_terms" (
    "unid" VARCHAR(32) NOT NULL,
    "title" VARCHAR(255),
    "subtitle" VARCHAR(255),
    "dict_value" VARCHAR(2),
    "content" LONGTEXT,
    "create_time" VARCHAR(32),
    "modify_time" VARCHAR(32),
    PRIMARY KEY ("unid")
);

CREATE TABLE "payment_terms_ardz" (
    "unid" VARCHAR(32) NOT NULL,
    "title" VARCHAR(255),
    "subtitle" VARCHAR(255),
    "dict_value" VARCHAR(2),
    "content" LONGTEXT,
    "create_time" VARCHAR(32),
    "modify_time" VARCHAR(32),
    PRIMARY KEY ("unid")
);

CREATE TABLE "payment_terms_enus" (
    "unid" VARCHAR(32) NOT NULL,
    "title" VARCHAR(255),
    "subtitle" VARCHAR(255),
    "dict_value" VARCHAR(2),
    "content" LONGTEXT,
    "create_time" VARCHAR(32),
    "modify_time" VARCHAR(32),
    PRIMARY KEY ("unid")
);

CREATE TABLE "payment_terms_frfr" (
    "unid" VARCHAR(32) NOT NULL,
    "title" VARCHAR(255),
    "subtitle" VARCHAR(255),
    "dict_value" VARCHAR(2),
    "content" LONGTEXT,
    "create_time" VARCHAR(32),
    "modify_time" VARCHAR(32),
    PRIMARY KEY ("unid")
);

